library FlutterTests;

final String AK =
"eyJ0eXAiOiJKV1QiLCJhbGciOiJzaGEyNTYifQ.eyJpc3MiOiJVU0VSIiwiYXVkIjoiMSoxKjEqMiozKiIsImV4cCI6MTY5NDA3Mjc5OCwiaWF0IjoxNjkzOTg2Mzk4LCJzdWIiOiIxMzY0ODQ2NjEiLCJjZHQiOiIwNi0wOS0yMDIzIn0.2SV-iMnQ0yoZoCc_wnpy3Q2IhivSK90f93RNH-Se-tY";
   List<String> localSearchArray = [];