library FlutterTests;

final String AK =
   "eyJ0eXAiOiJKV1QiLCJhbGciOiJzaGEyNTYifQ.eyJpc3MiOiJVU0VSIiwiYXVkIjoiMSoxKjEqMiozKiIsImV4cCI6MTY5Mzg5MzI0NywiaWF0IjoxNjkzODA2ODQ3LCJzdWIiOiIxMzY0ODQ2NjEiLCJjZHQiOiIwNC0wOS0yMDIzIn0.MWk4FnCCxI7oB8VF_XdEHq6IfCMZcA7WVj_AsDxYVe8";
List<String> localSearchArray = [];